export const CREATE_TASKS_ACTION = "CREATE_TASKS_ACTION";
export const CREATE_TASKS_ACTION_SUCCESS = "CREATE_TASKS_ACTION_SUCCESS";
export const CREATE_TASKS_ACTION_ERROR = "CREATE_TASKS_ACTION_ERROR";

export const FETCH_TASKS_ACTION = "FETCH_TASKS_ACTION";
export const FETCH_TASKS_ACTION_SUCCESS = "FETCH_TASKS_ACTION_SUCCESS";
export const FETCH_TASKS_ACTION_ERROR = "FETCH_TASKS_ACTION_ERROR";

export const REMOVE_TASKS_ACTION = "REMOVE_TASKS_ACTION";
export const REMOVE_TASKS_ACTION_SUCCESS = "REMOVE_TASKS_ACTION_SUCCESS";
export const REMOVE_TASKS_ACTION_ERROR = "REMOVE_TASKS_ACTION_ERROR";

export const UPDATE_TASK_ACTION = "UPDATE_TASK_ACTION";
export const UPDATE_TASK_ACTION_SUCCESS = "UPDATE_TASK_ACTION_SUCCESS";
export const UPDATE_TASK_ACTION_ERROR = "UPDATE_TASK_ACTION_ERROR";

export const GET_SINGLE_TASK_ACTION = "GET_SINGLE_TASK_ACTION";
export const GET_SINGLE_TASK_SUCCESS = "GET_SINGLE_TASK_SUCCESS";
export const GET_SINGLE_TASK_ERROR = "GET_SINGLE_TASK_ERROR";

export const SET_VALUE = "SET_VALUE";

export const HIDE_TOAST_ACTION = "HIDE_TOAST_ACTION";
